### ISSUE TITLE
com.canelmas.let.LetException: Delayed Execution Failed!

### ISSUE THREAD

**Issue by Zaldroc** [canelmas/let#16]
I'm getting following error using let:

```
`Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {de.fsrfb4.fb4/de.fsrfb4.fb4.TicketActivity}: com.canelmas.let.LetException: Delayed Execution Failed!
   at android.app.ActivityThread.deliverResults(ActivityThread.java:3758)
   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3801)
   at android.app.ActivityThread.access$1400(ActivityThread.java:157)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5551)
   at java.lang.reflect.Method.invoke(Method.java)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by com.canelmas.let.LetException: Delayed Execution Failed!
   at com.canelmas.let.Let.handle(Let.java:74)
   at de.fsrfb4.fb4.TicketActivity.onRequestPermissionsResult(TicketActivity.java:161)
   at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6588)
   at android.app.Activity.dispatchActivityResult(Activity.java:6467)
   at android.app.ActivityThread.deliverResults(ActivityThread.java:3754)
   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3801)
   at android.app.ActivityThread.access$1400(ActivityThread.java:157)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5551)
   at java.lang.reflect.Method.invoke(Method.java)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by com.canelmas.let.LetException: Future Task execution failed!
   at com.canelmas.let.DelayedTasks$Task.call(DelayedTasks.java:68)
   at com.canelmas.let.DelayedTasks$Task.execute(DelayedTasks.java:59)
   at com.canelmas.let.Let.handle(Let.java:72)
   at de.fsrfb4.fb4.TicketActivity.onRequestPermissionsResult(TicketActivity.java:161)
   at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6588)
   at android.app.Activity.dispatchActivityResult(Activity.java:6467)
   at android.app.ActivityThread.deliverResults(ActivityThread.java:3754)
   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3801)
   at android.app.ActivityThread.access$1400(ActivityThread.java:157)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5551)
   at java.lang.reflect.Method.invoke(Method.java)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)`
```

This is the corresponding code:

```
@AskPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
private void selectFile()
{
    showFileChooserDialog();
}

private void showFileChooserDialog()
{
    new FileChooserDialog.Builder(TicketActivity.this)
            .mimeType("application/pdf")
            .chooseButton(R.string.wählen)
            .cancelButton(R.string.abbrechen)
            .show();
}
```

What am i doing wrong?

**Comment by inlineTushar** [comment]
Any update on this issue ? I'm facing exactly the same problem!

**Comment by canelmas** [comment]
@tsaha-cse  Unfortunately not. 

Do you mind sharing any additional info if you have?
